In [1]:
import pandas as pd
import numpy as np

In [5]:
TAPP_2016 = pd.read_csv('TAPP 2016 Presidential Election Results.csv')
TAPP_2016.head()

,STATE,TOTAL VOTES,Democratic Votes,Democratic Vote %,Republican Votes,Republican Vote %,Libertarian Votes,Libertarian Vote %
0,Alabama,"2,123,372","729,547",34.40%,"1,318,255",62.10%,"44,467",2.10%
1,Alaska,"318,608","116,454",36.60%,"163,387",51.30%,"18,725",5.90%
2,Arizona,"2,573,165","1,161,167",45.10%,"1,252,401",48.70%,"106,327",4.10%
3,Arkansas,"1,130,635","380,494",33.70%,"684,872",60.60%,"29,829",2.60%
4,California,"14,181,595","8,753,788",61.70%,"4,483,810",31.60%,"478,500",3.40%

In [6]:
TAPP_2016.tail()

,STATE,TOTAL VOTES,Democratic Votes,Democratic Vote %,Republican Votes,Republican Vote %,Libertarian Votes,Libertarian Vote %
47,Washington,"3,209,214","1,742,718",54.30%,"1,221,747",38.10%,"160,879",5.00%
48,West Virginia,"713,051","188,794",26.50%,"489,371",68.60%,"23,004",3.20%
49,Wisconsin,"2,976,150","1,382,536",46.50%,"1,405,284",47.20%,"106,674",3.60%
50,Wyoming,"255,849","55,973",21.90%,"174,419",68.20%,"13,287",5.20%
51,Totals,"136,559,088","65,853,516",48.20%,"62,984,824",46.10%,"4,489,221",3.30%

In [7]:
TAPP_2012 = pd.read_csv('TAPP 2012 Presidential Election Results.csv')
TAPP_2008 = pd.read_csv('TAPP 2008 Presidential Election Results.csv')
TAPP_2004 = pd.read_csv('TAPP 2004 Presidential Election Results.csv')
TAPP_2000 = pd.read_csv('TAPP 2000 Presidential Election Results.csv')
TAPP_1996 = pd.read_csv('TAPP 1996 Presidential Election Results.csv')